[package]
name = "demo0016-rust-101"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
poc-framework = "0.1.0"
solend-token-lending = "0.1.1"